"""
This type stub file was generated by pyright.
"""

from ._api import YouTubeTranscriptApi
from ._transcripts import Transcript, TranscriptList
from ._errors import CookiePathInvalid, CookiesInvalid, CouldNotRetrieveTranscript, FailedToCreateConsentCookie, InvalidVideoId, NoTranscriptAvailable, NoTranscriptFound, NotTranslatable, TooManyRequests, TranscriptsDisabled, TranslationLanguageNotAvailable, VideoUnavailable, YouTubeRequestFailed

