"""
This type stub file was generated by pyright.
"""

class CouldNotRetrieveTranscript(Exception):
    """
    Raised if a transcript could not be retrieved.
    """
    ERROR_MESSAGE = ...
    CAUSE_MESSAGE_INTRO = ...
    CAUSE_MESSAGE = ...
    GITHUB_REFERRAL = ...
    def __init__(self, video_id) -> None:
        ...
    
    @property
    def cause(self): # -> Literal['']:
        ...
    


class YouTubeRequestFailed(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...
    def __init__(self, video_id, http_error) -> None:
        ...
    
    @property
    def cause(self): # -> str:
        ...
    


class VideoUnavailable(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class InvalidVideoId(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class TooManyRequests(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class TranscriptsDisabled(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class NoTranscriptAvailable(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class NotTranslatable(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class TranslationLanguageNotAvailable(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class CookiePathInvalid(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class CookiesInvalid(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class FailedToCreateConsentCookie(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...


class NoTranscriptFound(CouldNotRetrieveTranscript):
    CAUSE_MESSAGE = ...
    def __init__(self, video_id, requested_language_codes, transcript_data) -> None:
        ...
    
    @property
    def cause(self): # -> str:
        ...
    


